version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm insalling" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing stuff" # run the `echo` command
      - run: npm test a
  hithere: 
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: echo "hello"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere