export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCES = 'REQUEST_ROBOTS_SUCCES';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';